### ISSUE TITLE
ERROR: Service 'spark-mongo' failed to build: The command '/bin/sh -c wget -qO - ${SPARK_URL} | tar -xz -C /usr/local/     && cd /usr/local && ln -s ${SPARK_DIR} spark' returned a non-zero code: 2

### ISSUE THREAD

**Issue by mostafaghadimi** [JosemyD/docker-spark-mongo#5]
Hi @JosemyDuarte, I still have problem building the Dockerfile. Whenever I run the following docker-compose file I face with an error:
```
version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - 27017:27017

  spark-mongo:
    build: .
    # image: josemyd/docker-spark-mongo
    container_name: spark-mongo
    depends_on:
    - mongo
```

> ERROR: Service 'spark-mongo' failed to build: The command '/bin/sh -c wget -qO - ${SPARK_URL} | tar -xz -C /usr/local/     && cd /usr/local && ln -s ${SPARK_DIR} spark' returned a non-zero code: 2

I have tried many ways to run this image but I can't! I don't know where the problem is. Would you please give me a descriptive and complete instruction?
